require 'pry'
require 'nokogiri'
require 'open-uri'
require 'geocoder'
require 'colorize'
require 'watir'

require_relative '../lib/scraper'
require_relative '../lib/opportunity'
require_relative '../lib/cli'
require_relative '../lib/specific_scraper'